View all exercises
labseu2-workout-tracker/server pull request #12
Opened 2019-08-26 09:29 UTC by BenjaminGrabow

##  What does this PR do
This Pull Request sets up the Endpoint for getting all exercises.

##  Description of task to be completed
- Create findExercises in exercise-helpers.js

- Create GET endpoint for getting all exercises in exercise-routes.js

##  What are the relevant Trello board stories
- As a user I want to be able to view all the exercises:

https://trello.com/c/EBqfiwiJ/80-as-a-user-i-want-to-be-able-to-view-all-the-exercises

2019-08-26 09:32 UTC, BenjaminGrabow commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want to be able to view all the exercises.](https://trello.com/c/EBqfiwiJ/80-as-a-user-i-want-to-be-able-to-view-all-the-exercises)

2019-08-27 09:29 UTC, haywhyze commented on README.md
> +Individual exercise/workout endpoints to be /exercises/:id   or /workouts/:id
These comments should not be on the readme

2019-08-27 09:31 UTC, haywhyze commented on exercises/exercisesModels.js
> +function findExerciseById(id) {
If the Pull Request is to view all exercises, this function meant to get one exercise by id should not be included. I think Matt is already working on this.

2019-08-27 09:32 UTC, haywhyze commented on exercises/exercisesRoutes.js
> +router.get('/:id', async (req, res) => {
If the Pull Request is to view all exercises, this endpoint is meant to get one exercise by id should not be included. I think Matt is already working on this.

2019-08-27 09:35 UTC, haywhyze requested changes
This endpoint should be restricted to logged-in users. You might need to wait for @hyetigran to get his authentication ready before this task can be completed.

2019-08-27 13:05 UTC, shaunmcarmody approved these changes

2019-08-27 13:07 UTC, merged